### ISSUE TITLE
Crash when /setname and save world problem

### ISSUE THREAD

**Issue by ChickenCMB** [bedrock-tool/bedrocktool#107]
error?
when loading to another terrain
Version:
MC: 1.20.15
Tool: 1.31.1.8

Server: Hive

time="2023-09-17T10:15:03+07:00" level=info msg="Version: 1.31.1-8"
time="2023-09-17T10:15:03+07:00" level=info msg="Cmdline: [D:\\Downloads\\MCTool\\BedrockTool-Gui.exe]"
time="2023-09-17T10:15:03+07:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 193 [running]:
runtime/debug.Stack()
         /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/bedrock-tool/bedrocktool/utils.PrintPanic({0x1f62980?, 0xc002af20a8})
         /home/runner/work/bedrocktool/bedrocktool/utils/panic.go:20 +0x34
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1.1({0x1f62980?, 0xc002af20a8})
         /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:233 +0x2f
github.com/gregwebs/go-recovery.GoHandler(0xc00095d190, 0x0?)
         /home/runner/go/pkg/mod/github.com/gregwebs/go-recovery@v0.2.1/recovery.go:137 +0x43
github.com/gregwebs/go-recovery.Go(0xc001f33f98?)
         /home/runner/go/pkg/mod/github.com/gregwebs/go-recovery@v0.2.1/recovery.go:124 +0x25
created by github.com/bedrock-tool/bedrocktool/handlers/worlds.NewWorldsHandler.func6 in goroutine 130
         /home/runner/work/bedrocktool/bedrocktool/handlers/worlds/world.go:241 +0x9f

![Screenshot_3](https://github.com/bedrock-tool/bedrocktool/assets/145242044/09effb14-ceb1-46eb-82d2-7fc363f1f54a)

and when using /setname " " the tool crashes

**Comment by olebeck** [comment]
why are you setting the name to a single space, that is not a valid folder name in windows

**Comment by ChickenCMB** [comment]
> tại sao bạn lại đặt tên thành một khoảng trắng, đó không phải là tên thư mục hợp lệ trong windows

No it is the example /setname Map it crashes

**Comment by ChickenCMB** [comment]
> tại sao bạn lại đặt tên thành một khoảng trắng, đó không phải là tên thư mục hợp lệ trong windows

So is it fixed?, I close this issue?

**Comment by olebeck** [comment]
there was another issue that i found the problem for and fixed, this might be the same problem so try and see if it works now and if yes close the issue

**Comment by ChickenCMB** [comment]
> there was another issue that i found the problem for and fixed, this might be the same problem so try and see if it works now and if yes close the issue

![Screenshot_3](https://github.com/bedrock-tool/bedrocktool/assets/145242044/b9caf1a8-8697-464a-8513-11df441e62c6)
Why do I often have this problem? Is it because my connection and wifi are poor?

**Comment by ChickenCMB** [comment]
> there was another issue that i found the problem for and fixed, this might be the same problem so try and see if it works now and if yes close
