### ISSUE TITLE
error by packs command

### ISSUE THREAD

**Issue by not4syntaxpe** [bedrock-tool/bedrocktool#13]
```
time="2022-12-13T14:45:34+01:00" level=info msg="Version: v1.26.0"
time="2022-12-13T14:45:34+01:00" level=info msg="Cmdline: [C:\\Users\\Nick\\Downloads\\bedrocktool-v1.26.0_windows_amd64.exe packs]"
time="2022-12-13T14:45:34+01:00" level=error msg="Error: open keys.db: Access is denied."
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/debug/stack.go:24 +0x65
main.main.func1()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:32 +0x199
panic({0xed15a0, 0xc000f29680})
        /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
github.com/bedrock-tool/bedrocktool/utils.dump_keys(0xc000162000?)
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack.go:146 +0x545
github.com/bedrock-tool/bedrocktool/utils.(*ResourcePackCMD).Execute(0xc000008318, {0x10bff98, 0xc001474b40}, 0xc000787cf0?, {0x85c867?, 0x281f6cf4868?, 0x18?})
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack.go:223 +0x392
github.com/google/subcommands.(*Commander).Execute(0xc000162080, {0x10bff98, 0xc001474b40}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3bc
github.com/google/subcommands.Execute(...)
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:110 +0xaef
```

**Comment by olebeck** [comment]
are you using any special anti virus software that might be stopping programs from the internet modifiying files?

**Comment by not4syntaxpe** [comment]
I'm only use the Windows Defender

**Comment by xGAMEZAx** [comment]
i have same problem
