### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#170]
![image](https://github.com/bedrock-tool/bedrocktool/assets/124114223/61c97ffa-de0e-47d7-9733-79a049d8f215)

**Comment by HiveLanky** [comment]
time="2024-04-03T08:07:15-06:00" level=info msg="Bedrocktool Version 1.36.0-6"
time="2024-04-03T08:07:24-06:00" level=info msg="Listening on [::]:19132"
time="2024-04-03T08:07:24-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-04-03T08:07:33-06:00" level=info msg="Connecting to slayerspvp.com:19132"
time="2024-04-03T08:07:35-06:00" level=debug msg="received remote pack infos"
time="2024-04-03T08:07:36-06:00" level=debug msg="waiting for remote stack"
time="2024-04-03T08:07:36-06:00" level=debug msg="received remote resourcepack stack, starting game"
time="2024-04-03T08:07:37-06:00" level=info msg="couldnt determine game version, assuming > 1.18"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'Float64'"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'"
time="2024-04-03T08:07:37-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'"
Fatal Error occurred.
--COPY FROM HERE--
Version: 1.36.0-6
Cmdline: [C:\Users\LiamM\Downloads\bedrocktool-windows-amd64-1.36.0-6-gui.exe]
Error: runtime error: makeslice: len out of range
stacktrace from panic: 
goroutine 116 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/bedrock-tool/bedrocktool/utils.PrintPanic({0x1dd5760?, 0x1dcfd70})
	/home/runner/work/bedrocktool/bedrocktool/utils/panic.go:21 +0x34
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1.1({0x1dd5760?, 0x1dcfd70})
	/home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:251 +0x2f
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).packetFunc.func1()
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:235 +0x3b
panic({0x1a3fa60?, 0x1dcfd70?})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x21f
github.com/sandertv/gophertunnel/minecraft/nbt.networkLittleEndian.Int32Slice({{}}, 0xc000def920?)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/encoding.go:194 +0x45
github.com/sandertv/gophertunnel/minecraft/nbt.(*Decoder).unmarshalTag(0xc001b5d698, {0x1a30cc0?, 0xc00051c1e0?, 0x2ba12fa0108?}, 0xb, {0xc000dd465c, 0x1})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/decode.go:238 +0x24d2
github.com/sandertv/gophertunnel/minecraft/nbt.(*Decoder).Decode(0xc001b5d698, {0x19bba20?, 0xc00051c1e0?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/decode.go:52 +0x16b
github.com/df-mc/dragonfly/server/world/chunk.NetworkDecode(0x38?, {0xc001b14000, 0x226, 0x226}, 0x0, 0x0, 0xd7?, {0xffffffffffffffc0, 0x13f})
	/home/runner/work/bedrocktool/bedrocktool/dragonfly/server/world/chunk/decode.go:89 +0x4ce
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).processLevelChunk(0xc0001e8840, 0xc001b12370)
	/home/runner/work/bedrocktool/bedrocktool/handlers/worlds/chunk.go:43 +0x125
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).chunkPackets(0xc0001e8840?, {0x1de0628?, 0xc001b12370?})
	/home/runner/work/bedrocktool/bedrocktool/handlers/worlds/packets.go:240 +0x59
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).packetCB(0xc0001e8840, {0x1de0628?, 0xc001b12370?}, 0x8e?, {0xc17b768a652e2bc2?, 0x57a1dc5f3?, 0x2cb4980?}, 0x86?)
	/home/runner/work/bedrocktool/bedrocktool/handlers/worlds/packets.go:123 +0x3df
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).packetFunc(0xc000181500, {0x1b11110?, 0xc0?, 0x0?}, {0xc001adf387, 0x233, 0xc79}, {0x1dded90?, 0xc001d8b0e0}, {0x1dded90, ...})
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:267 +0x323
github.com/sandertv/gophertunnel/minecraft.(*Conn).PacketFunc(0xc001b11110?, {0x1b5ddd8?, 0xc0?, 0x0?}, {0xc001adf387?, 0xc001b5ddf8?, 0x146fc66?}, {0x1dded90?, 0xc001d8b0e0?}, {0x1dded90, ...})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:250 +0x5d
github.com/sandertv/gophertunnel/minecraft.parseData({0xc001adf386, 0x234, 0xc7a}, {0x1dfdd08, 0xc001c4a000}, {0x1dded90, 0xc001d8b0e0}, {0x1dded90, 0xc001d8b0b0})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/packet.go:28 +0x1a6
github.com/sandertv/gophertunnel/minecraft.(*Conn).receive(0xc001c4a000, {0xc001adf386, 0x234, 0xc7a})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/conn.go:626 +0xb3
github.com/sandertv/gophertunnel/minecraft.listenConn(0xc001c4a000, 0xc0007d59e0?, 0x12?, 0x0?)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:325 +0x1ea
created by github.com/sandertv/gophertunnel/minecraft.Dialer.DialContext in goroutine 13
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/dial.go:247 +0xb9d

--END COPY HERE--
