### ISSUE TITLE
Panic on world download

### ISSUE THREAD

**Issue by Adrian8115** [bedrock-tool/bedrocktool#177]
I tried download the Hive world with mcbe 1.20.80 and it paniced with the following info:
```
Version: 1.37.0-3
Cmdline: [D:\user\adria\Downloads\bedrocktool-windows-amd64-1.37.0-3-gui.exe]
Error: interface conversion: interface {} is messages.Features, not *messages.Features
stacktrace from panic:
goroutine 29 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/bedrock-tool/bedrocktool/utils.PrintPanic({0x204f6e37f58?, 0xc002980420})
        /home/runner/work/bedrocktool/bedrocktool/utils/panic.go:21 +0x34
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1.1({0x204f6e37f58?, 0xc002980420})
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:251 +0x2f
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1.2()
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:260 +0x3b
panic({0x1863f60?, 0xc002980420?})
        /opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x21f
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*MapUI).Start(0xc0000a6a80, {0x1c06d70?, 0xc000f345f0})
        /home/runner/work/bedrocktool/bedrocktool/handlers/worlds/map_item.go:106 +0x378
github.com/bedrock-tool/bedrocktool/handlers/worlds.NewWorldsHandler.func5()
        /home/runner/work/bedrocktool/bedrocktool/handlers/worlds/world.go:266 +0x348
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).doSession(0xc000228380, {0x1c06d70?, 0xc000f34960}, 0xc000938c50)
        /home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:443 +0x10a7
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).connect(0xc000228380, {0x1c06d70, 0xc000f345a0})
        /home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:502 +0x16a
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).Run(0xc000228380, {0x1c06d70, 0xc000f345a0}, {0xc00110e330?, 0x17cba60?})
        /home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:611 +0x75c
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute(0xc001900120, {0x1c06d70, 0xc000f345a0})
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:74 +0x2f7
github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute.func1()
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:264 +0x133
created by github.com/bedrock-tool/bedrocktool/ui/gui/pages.(*Router).Execute in goroutine 1
        /home/runner/work/bedrocktool/bedrocktool/ui/gui/pages/router.go:246 +0xa5
```

**Comment by olebeck** [comment]
fixed

**Comment by Adrian8115** [comment]
thx!
