### ISSUE TITLE
Realm Downloader Crashes

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#191]
Realm Downloader Crashes

Steps to do this:
Download the latest one currently for me it is 1.38.0-13
go to Worlds
click realms
Click which realm
Connect to 127.0.0.1
app crashes

**Comment by HiveLanky** [comment]
time="2024-06-30T07:39:31-06:00" level=info msg="Bedrocktool Version 1.38.0-15" part=main
time="2024-06-30T07:40:04-06:00" level=error msg="APIError 403 403 No valid subscription"
time="2024-06-30T07:40:16-06:00" level=info msg="Listening on [::]:19132"
time="2024-06-30T07:40:16-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-06-30T07:40:21-06:00" level=info msg="Connecting to 104.42.10.202:30200"
time="2024-06-30T07:40:24-06:00" level=warning msg="duplicate texture pack entry a94fb9b1-41c7-4a28-aa76-eb5057a79064 in resource pack info\n" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=warning msg="duplicate texture pack entry 152fe5a4-9a44-461a-9dc4-187188aed939 in resource pack info\n" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=warning msg="duplicate texture pack entry 5d8314d4-b879-406c-85b3-3071de21ae89 in resource pack info\n" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=debug msg="received remote pack infos" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=debug msg="waiting for remote stack" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=info msg="pack ffca3a68-4bd3-4118-be08-931d01315e88_1.0.0 had a different size in the ResourcePacksInfo packet than the ResourcePackDataInfo packet\n" part=ResourcePacks
time="2024-06-30T07:40:24-06:00" level=info msg="pack 19e34e2c-e4bb-11eb-ba80-0242ac130004_1.0.2 had a different size in the ResourcePacksInfo packet than the ResourcePackDataInfo packet\n" part=ResourcePacks
time="2024-06-30T07:40:25-06:00" level=info msg="pack 9a9f84bf-714d-4c9d-92f2-34525223edea_1.0.0 had a different size in the ResourcePacksInfo packet than the ResourcePackDataInfo packet\n" part=ResourcePacks
time="2024-06-30T07:40:26-06:00" level=info msg="pack a94fb9b1-41c7-4a28-aa76-eb5057a79064_1.0.0 had a different size in the ResourcePacksInfo packet than the ResourcePackDataInfo packet\n" part=ResourcePacks
time="2024-06-30T07:40:26-06:00" level=info msg="pack 914350e8-9e9b-11ed-a8fc-0242ac120002_1.0.0 had a different size in the ResourcePacksInfo packet than the ResourcePackDataInfo packet\n" part=ResourcePacks
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xf3d6a2]

goroutine 104 [running]:
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).downloadResourcePack(0xc000c7e8c0, 0xc0005a2b80)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:337 +0x702
github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo.func4()
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:254 +0x65
created by github.com/bedrock-tool/bedrocktool/utils/proxy.(*rpHandler).OnResourcePacksInfo in goroutine 143
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/resourcepacks.go:252 +0x14ec

**Comment by olebeck** [comment]
can you try latest update, it should be fixed. i cant test since i dont have access to that realm

**Comment by HiveLanky** [comment]
Unable to get it working
