### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by HiveLanky** [bedrock-tool/bedrocktool#199]
time="2024-07-06T16:27:17-06:00" level=warning msg="invalid geometry" part=WorldsHandler player=oSynixx
time="2024-07-06T16:27:20-06:00" level=info msg="Saving world §aEons§r | §0Black Hole with 198 Chunks" part=WorldsHandler
time="2024-07-06T16:27:20-06:00" level=debug msg="Opening provider in worlds/play.eonsmc.net/§aEons§r | §0Black Hole" part=world
time="2024-07-06T16:27:20-06:00" level=error msg="open db: level.dat: open file: open worlds\\play.eonsmc.net\\§aEons§r | §0Black Hole\\level.dat: The filename, directory name, or volume label syntax is incorrect." part=WorldsHandler
time="2024-07-06T16:27:21-06:00" level=error msg="write packet minecraft [::]:19132->127.0.0.1:63393: use of closed network connection" part=MapUI

App Crash

**Comment by HiveLanky** [comment]
time="2024-07-06T16:27:02-06:00" level=info msg="Bedrocktool Version 1.38.0-24" part=main
time="2024-07-06T16:27:05-06:00" level=info msg="Listening on [::]:19132"
time="2024-07-06T16:27:05-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-07-06T16:27:08-06:00" level=info msg="Connecting to play.eonsmc.net:19245"
time="2024-07-06T16:27:10-06:00" level=debug msg="received remote pack infos" part=ResourcePacks
time="2024-07-06T16:27:10-06:00" level=debug msg="waiting for remote stack" part=ResourcePacks
time="2024-07-06T16:27:10-06:00" level=debug msg="received remote resourcepack stack, starting game" part=ResourcePacks
time="2024-07-06T16:27:11-06:00" level=info msg="Using Custom Blocks" part=WorldsHandler
time="2024-07-06T16:27:11-06:00" level=warning msg="invalid geometry" part=WorldsHandler player=oSynixx
time="2024-07-06T16:27:15-06:00" level=debug msg="Connected to server."

time="2024-07-06T16:27:17-06:00" level=warning msg="invalid geometry" part=WorldsHandler player=oSynixx
time="2024-07-06T16:27:20-06:00" level=info msg="Saving world §aEons§r | §0Black Hole with 198 Chunks" part=WorldsHandler
time="2024-07-06T16:27:20-06:00" level=debug msg="Opening provider in worlds/play.eonsmc.net/§aEons§r | §0Black Hole" part=world
time="2024-07-06T16:27:20-06:00" level=error msg="open db: level.dat: open file: open worlds\\play.eonsmc.net\\§aEons§r | §0Black Hole\\level.dat: The filename, directory name, or volume label syntax is incorrect." part=WorldsHandler
time="2024-07-06T16:27:21-06:00" level=error msg="write packet minecraft [::]:19132->127.0.0.1:63393: use of closed network connection" part=MapUI
time="2024-07-06T16:28:45-06:00" level=info msg="Listening on [::]:19245"
time="2024-07-06T16:28:45-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-07-06T16:29:09-06:00" level=info msg="Listening on [::]:19132"
time="2024-07-06T16:29:09-06:00" level=info msg="Open Minecraft and connect to this computers local ip address to continue"
time="2024-07-06T16:29:16-06:00" level=info msg="Connecting to play.eonsmc.net:19245"
time="2024-07-06T16:29:18-06:00" level=debug msg="received remote pack infos" part=ResourcePacks
time="2024-07-06T16:29:18-06:00" level=debug msg="waiting for remote stack" part=ResourcePacks
time="2024-07-06T16:29:18-06:00" level=debug msg="received remote resourcepack stack, starting game" part=ResourcePacks
time="2024-07-06T16:29:19-06:00" level=info msg="Using Custom Blocks" part=WorldsHandler
time="2024-07-06T16:29:19-06:00" level=warning msg="invalid geometry" part=WorldsHandler player=oSynixx
time="2024-07-06T16:29:23-06:00" level=debug msg="Connected to server."

time="2024-07-06T16:29:25-06:00" level=warning msg="invalid geometry" part=WorldsHandler player=oSynixx
time="2024-07-06T16:29:27-06:00" level=info msg="Saving world §aEons§r | §0Black Hole with 185 Chunks" part=WorldsHandler
time="2024-07-06T16:29:27-06:00" level=debug msg="Opening provider in worlds/play.eonsmc.net/§aEons§r | §0Black Hole" part=world
time="2024-07-06T16:29:27-06:00" level=error msg="open db: level.dat: open file: open worlds\\play.eonsmc.net\\§aEons§r | §0Black Hole\\level.dat: The filename, directory name, or volume label syntax is incorrect." part=WorldsHandler
time="2024-07-06T16:29:28-06:00" level=error msg="write packet minecraft [::]:19132->127.0.0.1:63393: use of closed network connection" part=MapUI

**Comment by HiveLanky** [comment]
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:38-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=debug msg="Opening provider in worlds/play.eonsmc.net/§aEons§r | §0Black Hole" part=world
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '26' at offset 16 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '23' at offset 14 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '15' at offset 14 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '17' at offset 9 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '20' at offset 11 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '18' at offset 8 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '20' at offset 10 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '17' at offset 8 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '19' at offset 9 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="nbt: unknown tag '15' at offset 10 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:39-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '22' at offset 8 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '21' at offset 14 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: varint did not terminate after 5 bytes at offset 6" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '21' at offset 8 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '18' at offset 6 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'StringLength'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '19' at offset 6 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '13' at offset 8 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '20' at offset 6 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '13' at offset 6 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '26' at offset 6 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '19' at offset 3 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '20' at offset 2 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: invalid type for tag '' at offset 3: cannot unmarshal TAG_Long into map[string]interface {}" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '20' at offset 2 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unexpected buffer end during op: 'String'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '19' at offset 18 during op 'Match'" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: invalid type for tag '' at offset 3: cannot unmarshal TAG_Long into map[string]interface {}" part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="bug check: subchunk received before chunk" packet=SubChunk part=WorldsHandler
time="2024-07-06T16:34:40-06:00" level=error msg="nbt: unknown tag '19' at offset 5 during op 'Match'" part=WorldsHandler
panic: runtime error: makeslice: len out of range

goroutine 236 [running]:
github.com/sandertv/gophertunnel/minecraft/nbt.networkLittleEndian.Int32Slice({{}}, 0xc005d44ea0)
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/encoding.go:194 +0x45
github.com/sandertv/gophertunnel/minecraft/nbt.(*Decoder).unmarshalTag(0xc0028f6cb8, {0x1c52060?, 0xc0028a28d8?, 0xc005d44ed0?}, 0xb, {0xc005041a40, 0x5})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/decode.go:238 +0x24f9
github.com/sandertv/gophertunnel/minecraft/nbt.(*Decoder).Decode(0xc0028f6cb8, {0x1bda5a0?, 0xc0028a28d8?})
	/home/runner/work/bedrocktool/bedrocktool/gophertunnel/minecraft/nbt/decode.go:52 +0x16b
github.com/df-mc/dragonfly/server/world/chunk.NetworkDecode({0x2026980?, 0xc001fb8100?}, {0xc005d40a00, 0x3054, 0x3054}, 0x0, 0x0, 0x1, {0xffffffffffffffc0, 0x13f})
	/home/runner/work/bedrocktool/bedrocktool/dragonfly/server/world/chunk/decode.go:86 +0x513
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).processLevelChunk(0xc0001ccf20, 0xc004d291d0)
	/home/runner/work/bedrocktool/bedrocktool/handlers/worlds/chunk.go:36 +0x12b
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*worldsHandler).packetCB(0xc0001ccf20, {0x2011838, 0xc004d291d0}, 0x3a?, {0xc0028f7a20?, 0x102afc5?, 0x2f31da0?}, 0xd0?)
	/home/runner/work/bedrocktool/bedrocktool/handlers/worlds/packets.go:141 +0x445
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).proxyLoop(0xc004f86008, {0x20178d0, 0xc001270730}, 0x0)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:164 +0x49f
github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).doSession.func7(0x0?)
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:493 +0x67
created by github.com/bedrock-tool/bedrocktool/utils/proxy.(*Context).doSession in goroutine 204
	/home/runner/work/bedrocktool/bedrocktool/utils/proxy/context.go:503 +0x136d
