### ISSUE TITLE
Error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#45]
```
time="2023-02-22T23:25:15+07:00" level=info msg="Version: v1.27.0-1-ge532089"
time="2023-02-22T23:25:15+07:00" level=info msg="Cmdline: [C:\\Users\\Admin\\Downloads\\bedrocktool\\bedrocktool-v1.27.0-1-ge532089_windows_386.exe packs]"
time="2023-02-22T23:25:15+07:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x83
main.main.func1()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:38 +0x240
panic({0xcf30e0, 0x1765dd8})
        /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x1ba
github.com/sandertv/gophertunnel/minecraft.(*Conn).ResourcePacks(...)
        /home/runner/go/pkg/mod/github.com/olebeck/gophertunnel@v1.27.3-3/minecraft/conn.go:393
github.com/bedrock-tool/bedrocktool/utils.(*ResourcePackCMD).Execute.func1(0x13484090, {0xed1bb0, 0x12966720})
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack-ace.go:211 +0xa0
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run(0x13484090, {0xed8560, 0x13484060}, {0x133f8030, 0x16})
        /home/runner/work/bedrocktool/bedrocktool/utils/proxy.go:300 +0xb33
github.com/bedrock-tool/bedrocktool/utils.(*ResourcePackCMD).Execute(0x12808b10, {0xed8560, 0x134853b0}, 0x13406030, {0x0, 0x0, 0x0})
        /home/runner/work/bedrocktool/bedrocktool/utils/resourcepack-ace.go:269 +0x1d9
github.com/google/subcommands.(*Commander).Execute(0x12862e80, {0xed8560, 0x134853b0}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x2d4
github.com/google/subcommands.Execute(...)
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:154 +0x13fa
```

**Comment by olebeck** [comment]
that likely means there was an error connecting

**Comment by olebeck** [comment]
Has the error been fixed / are you getting a clearer error message?

**Comment by NhanAZ** [comment]
I'm not sure, I can't reproduce this error every time

**Comment by olebeck** [comment]
have you had this error since, if not please close the issue

**Comment by NhanAZ** [comment]
Maybe this has been fixed, thank you.
