### ISSUE TITLE
Error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by NhanAZ** [bedrock-tool/bedrocktool#6]
```shell
time="2022-11-01T13:10:25+07:00" level=info msg="Version: v1.24.12"
time="2022-11-01T13:10:25+07:00" level=info msg="Cmdline: [D:\\Downloads\\bedrocktool-v1.24.12_windows_amd64.exe worlds]"
time="2022-11-01T13:10:25+07:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.main.func1()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:32 +0x199
panic({0x139fc20, 0x1d888e0})
        /opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).SaveAndReset(0xc0009d8370)
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:343 +0x61f
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute(0xc000770018, {0x15ad5d8?, 0xc001066040}, 0xc000109cf0?, {0xd4c867?, 0x1dcb916f7c0?, 0x18?})
        /home/runner/work/bedrocktool/bedrocktool/subcommands/world/world.go:178 +0x2b7
github.com/google/subcommands.(*Commander).Execute(0xc00015a080, {0x15ad5d8, 0xc001066040}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3bc
github.com/google/subcommands.Execute(...)
        /home/runner/go/pkg/mod/github.com/google/subcommands@v1.2.0/subcommands.go:492
main.main()
        /home/runner/work/bedrocktool/bedrocktool/cmd/bedrocktool/main.go:110 +0xaef
```

**Comment by olebeck** [comment]
new version should fix that bug
