### ISSUE TITLE
Proxy crashes on galaxite

### ISSUE THREAD

**Issue by McMelonTV** [bedrock-tool/bedrocktool#62]
**Describe the bug**
The proxy crashes on galaxite when moving into chronos

**To Reproduce**
1. Go to Galaxite
2. Join Chronos
3. Wait till the queue and countdown is up
4. The proxy crashes when the server wants to move you to chronos

**Expected behavior**
The world should change as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/62901799/227608318-d2e7e076-07d1-4c08-90d6-96f53c7187e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version r1.28.0

**Additional context**

panic: runtime error: index out of range [8] with length 8

goroutine 128 [running]:
github.com/df-mc/dragonfly/server/world/chunk.NetworkDecode(0xfffffffe?, {0xc00c7ba000, 0x1350, 0x1350}, 0x10, {0x0, 0x7f}, 0x1, 0x0?)
        github.com/df-mc/dragonfly@v0.9.3/server/world/chunk/decode.go:29 +0x875
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).processLevelChunk(0xc000a620c0, 0xc00c7b2910)
        github.com/bedrock-tool/bedrocktool/subcommands/world/chunk.go:37 +0xe9
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).ProcessChunkPackets(0xc000a620c0, {0xf7d7e8?, 0xc00c7b2910?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/chunk.go:116 +0x79
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute.func2({0xf7d7e8?, 0xc00c7b2910?}, 0xc0?, {0x24?, 0x0?, 0x185ade0?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/world.go:177 +0x75
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).proxyLoop(0xc00113fa90?, {0xf82078, 0xc001c6d270}, 0x0, {0xc000376ec0, 0x2, 0xc0008418c0?})
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:229 +0x184
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run.func2()
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:345 +0x72
created by github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:343 +0xd0f

**Comment by olebeck** [comment]
does this error happen consistently, i playyed a full round of that game mode and it worked fine

**Comment by McMelonTV** [comment]
It happened everytime I tried to join chronos. I can try one more time though

**Comment by McMelonTV** [comment]
Yep, it happened again
![image](https://user-images.githubusercontent.com/62901799/227731431-7b5375ad-ac52-4229-b3d6-b21bc132bf6d.png)


panic: runtime error: index out of range [8] with length 8

goroutine 56 [running]:
github.com/df-mc/dragonfly/server/world/chunk.NetworkDecode(0xfffffffa?, {0xc0001d43c0, 0x121, 0x121}, 0x10, {0x0, 0x7f}, 0x1, 0x0?)
        github.com/df-mc/dragonfly@v0.9.3/server/world/chunk/decode.go:29 +0x875
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).processLevelChunk(0xc001be8180, 0xc005344000)
        github.com/bedrock-tool/bedrocktool/subcommands/world/chunk.go:37 +0xe9
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldState).ProcessChunkPackets(0xc001be8180, {0xfbd7e8?, 0xc005344000?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/chunk.go:116 +0x79
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute.func2({0xfbd7e8?, 0xc005344000?}, 0x0?, {0xc000d0f9f0?, 0xc00018c200?, 0x189ade0?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/world.go:177 +0x75
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).proxyLoop(0xc0022be3c0?, {0xfc2078, 0xc001ab5040}, 0x0, {0xc001bc0490, 0x2, 0xc001b58850?})
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:229 +0x184
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run.func2()
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:345 +0x72
created by github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:343 +0xd0f

**Comment by Buddelbubi** [comment]
Got something similar on my own server.

level=info msg="konnte die Spieleversion nicht bestimmen, gehe davon aus, dass es > 1.18 ist"
panic: runtime error: index out of range [4] with length 0

goroutine 62 [running]:
github.com/bedrock-tool/bedrocktool/subcommands/world.(*worldsServer).processItemPacketsServer(0xc000d0e000, {0xd40cc8?, 0xc000c48d80?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/items.go:46 +0xad4
github.com/bedrock-tool/bedrocktool/subcommands/world.(*WorldCMD).Execute.func3({0xd40cc8?, 0xc000c48d80?}, 0x40?, {0xc0009befc0?, 0xc000564000?, 0x14fddc0?})
        github.com/bedrock-tool/bedrocktool/subcommands/world/world.go:192 +0x65
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).proxyLoop(0xc000ad3fb0?, {0xd456b8, 0xc0007bd3b0}, 0x0, {0xc0004be270, 0x2, 0x100010000?})
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:233 +0x184
github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run.func2()
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:354 +0x72
created by github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run
        github.com/bedrock-tool/bedrocktool/utils/proxy.go:352 +0xe2f
