### ISSUE TITLE
Error when trying to download a pack

### ISSUE THREAD

**Issue by xxAROX** [bedrock-tool/bedrocktool#80]
```
--COPY FROM HERE--                                                                                                      time="2023-06-27T20:50:26+02:00" level=info msg="Version: 1.30.0-6"                                                     time="2023-06-27T20:50:26+02:00" level=info msg="Cmdline: [C:\\Users\\kfeig\\Documents\\BEDROCKTOOL\\.bedrocktool-windows-amd64-1.30.0-1.exe packs]"                                                                                            time="2023-06-27T20:50:26+02:00" level=error msg="Error: runtime error: invalid memory address or nil pointer dereference"                                                                                                                      stacktrace from panic:                                                                                                  goroutine 1 [running]:                                                                                                  runtime/debug.Stack()                                                                                                           runtime/debug/stack.go:24 +0x65                                                                                 main.main.func1()                                                                                                               github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:87 +0x1c5                                           panic({0xf290c0, 0x191acc0})                                                                                                    runtime/panic.go:884 +0x213                                                                                     github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d.(*ResourcePackHandler).PacketFunc(0xc0012441d8?, {0x72de8a?, 0x0?, 0x0?}, {0xc00008a202, 0x4, 0xfe}, {0xc000500000?, 0x72e267?}, {0x1175230, ...})                                       github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d/resourcepack-d.go:261 +0x47                      github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run.func3({0x143eaf8?, 0xc0?, 0x0?}, {0xc00008a202, 0x4, 0xfe}, {0x1175230?, 0xc001192690?}, {0x1175230, 0xc0011926c0})                                                                       github.com/bedrock-tool/bedrocktool/utils/proxy.go:437 +0xed                                                    github.com/sandertv/gophertunnel/minecraft.(*Conn).WritePacket(0xc0011f7700, {0x1174588, 0xc0014398c0})                         github.com/sandertv/gophertunnel@v1.30.0/minecraft/conn.go:396 +0x3ee                                           github.com/sandertv/gophertunnel/minecraft.Dialer.DialContext({0xc0011ae0a0, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, ...}, ...}, ...)                                                                                                       github.com/sandertv/gophertunnel@v1.30.0/minecraft/dial.go:235 +0xb5a                                           github.com/bedrock-tool/bedrocktool/utils.connectServer({0x1178a58, 0xc000f01ae0}, {0xc001186018, 0x13}, 0xece9c0?, 0x1, 0xc001182300, {0x116de00, 0xc0011921b0})                                                                                       github.com/bedrock-tool/bedrocktool/utils/utils.go:75 +0x2c5                                                    github.com/bedrock-tool/bedrocktool/utils.(*ProxyContext).Run(0xc0011a8230, {0x1178a58?, 0xc000f01ae0}, {0xc001186018, 0x13}, {0xc001186018, 0xd})                                                                                                      github.com/bedrock-tool/bedrocktool/utils/proxy.go:447 +0x893                                                   github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d.Execute_cmd({0x1178a58, 0xc000f01ae0}, {0x0?, 0x1172d00?}, 0x0, 0x0)                                                                                                                     github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d/resourcepack-d.go:302 +0x25d                     github.com/bedrock-tool/bedrocktool/subcommands.(*ResourcePackCMD).Execute(0xc000044410?, {0x1178a58?, 0xc000f01ae0?}, {0x83a4af?, 0xe0eb82?})                                                                                                          github.com/bedrock-tool/bedrocktool/subcommands/resourcepack-d.go:30 +0x3c                                      github.com/bedrock-tool/bedrocktool/utils.(*cmdWrap).Execute(0xc0005f0060?, {0x1178a58?, 0xc000f01ae0?}, 0xc000500400?, {0xc00118c000?, 0x0?, 0xc000589c80?})                                                                                           github.com/bedrock-tool/bedrocktool/utils/command_register.go:31 +0x3e                                          github.com/google/subcommands.(*Commander).Execute(0xc000ba3700, {0x1178a58, 0xc000f01ae0}, {0x0, 0x0, 0x0})                    github.com/google/subcommands@v1.2.0/subcommands.go:209 +0x3a2                                                  github.com/google/subcommands.Execute(...)                                                                                      github.com/google/subcommands@v1.2.0/subcommands.go:492                                                         github.com/bedrock-tool/bedrocktool/utils.(*InteractiveCLI).Start(0xc000f9e600?, {0x1178a58, 0xc000f01ae0}, 0xc000f99820)                                                                                                                               github.com/bedrock-tool/bedrocktool/utils/iui.go:82 +0x3d7                                                      main.main()                                                                                                                     github.com/bedrock-tool/bedrocktool/cmd/bedrocktool/main.go:162 +0x945                                                                                                                                                                  --END COPY HERE--
```

**Comment by olebeck** [comment]
i cant test myself, i just uploaded an update with a fix for this. should be fixed now reopen if not
