### ISSUE TITLE
World downloader crash

### ISSUE THREAD

**Issue by Fleecks** [bedrock-tool/bedrocktool#98]
`INFO[0005] Open Minecraft and connect to this computers local ip address to continue
INFO[0141] Connecting to bandomas.pro:19132       
DEBU[0145] received remote pack infos             
DEBU[0145] waiting for remote stack               
DEBU[0145] received remote resourcepack stack, starting game
INFO[0147] Using Custom Blocks                    
INFO[0147] couldnt determine game version, assuming > 1.18
DEBU[0148] Connected to server.                   
ERRO[0193] hujson: line 1, column 1: parsing value: unexpected EOF
ERRO[0193] hujson: line 1, column 1: parsing value: unexpected EOF
panic: runtime error: index out of range [35176] with length 16674

goroutine 182 [running]:
github.com/df-mc/dragonfly/server/world/chunk.(*Chunk).HighestBlockLayer(0xc0002bc100, 0x0?, 0x0?, 0x0, 0x0)
        github.com/df-mc/dragonfly/server/world/chunk/chunk.go:208 +0x169
github.com/df-mc/dragonfly/server/world/chunk.(*Chunk).HeightMapWithWater(0xc0002bc100)
        github.com/df-mc/dragonfly/server/world/chunk/chunk.go:240 +0x77
github.com/bedrock-tool/bedrocktool/utils.Chunk2Img(0xc000bef950?)
        github.com/bedrock-tool/bedrocktool/utils/chunk_render.go:140 +0x38
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*MapUI).processQueue(0xc000c65e30)
        github.com/bedrock-tool/bedrocktool/handlers/worlds/map_item.go:205 +0xee
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*MapUI).Redraw(0xc000c65e30)
        github.com/bedrock-tool/bedrocktool/handlers/worlds/map_item.go:229 +0x2a
github.com/bedrock-tool/bedrocktool/handlers/worlds.(*MapUI).Start.func2()
        github.com/bedrock-tool/bedrocktool/handlers/worlds/map_item.go:133 +0x12f
created by github.com/bedrock-tool/bedrocktool/handlers/worlds.(*MapUI).Start in goroutine 1
        github.com/bedrock-tool/bedrocktool/handlers/worlds/map_item.go:122 +0x1e5`

**Comment by Fleecks** [comment]
The problem occurs only with a specific server (I tried with LifeBoat and there were no problems)

**Comment by olebeck** [comment]
what server

**Comment by Fleecks** [comment]
> what server

bandomas.pro, but this is a private server

**Comment by olebeck** [comment]
run with -extra-debug and upload the packets.log

**Comment by Fleecks** [comment]
> run with -extra-debug and upload the packets.log

[packets.log](https://github.com/bedrock-tool/bedrocktool/files/12468566/packets.log)
